language: elixir
elixir:
  - 1.2.1
otp_release:
  - 18.2.1
sudo: false # to use faster container based build environment
after_script:
  - mix deps.get --only docs
  - MIX_ENV=docs mix inch.report
notifications:
  recipients:
    - mikalai.seva@gmail.com
